language: cpp
env:
  - GOARCH=amd64
  - GO_VERSION=1.7.1
matrix:
  include:
    - os: osx
      env: GOOS=darwin
    - os: linux
      env: GOOS=linux
    - os: linux
      env: GOOS=freebsd
    - os: linux
      env: GOOS=windows
    - os: linux
      env: GOOS=openbsd
    - os: linux
      env: GOOS=netbsd
    - os: linux
      env: GOOS=solaris
branches:
  only:
  - master
install: ./.travis/install-go.sh
script: ./.travis/build.sh
cache:
  directories:
  - $HOME/cache/$TRAVIS_REPO_SLUG
