name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest version from tags and releases
        id: get_latest_version
        run: |
          # get Latest Git tag name
          latest_tag=$(git tag -l "v*" | sort -V | tail -n1)
          if [ -z "$latest_tag" ]; then
            latest_tag="v0.0.0"
          fi
          echo "Latest tag: $latest_tag"

          # get Latest GitHub Release version
          latest_release=$(gh release view --json tagName -q .tagName 2>/dev/null || echo "v0.0.0")
          echo "Latest release: $latest_release"

          final_version=$(printf '%s\n' "$latest_tag" "$latest_release" | sort -V | tail -n1)

          echo "Final version: $final_version"
          echo "LATEST_RELEASE=$final_version" >> $GITHUB_ENV

      - name: Calculate next version
        id: calc_version
        run: |
          version=${{ env.LATEST_RELEASE }}
          IFS='.' read -r base major minor <<< "${version//v/}"

          # Increment minor version
          minor=$((minor + 1))

          # Check if minor exceeds 999
          if ((minor > 999)); then
              minor=0
              major=$((major + 1))
          fi

          # Check if major exceeds 999
          if ((major > 999)); then
              major=0
              base=$((base + 1))
          fi

          next_version="v${base}.${major}.${minor}"
          echo "Next version: $next_version"
          echo "NEXT_VERSION=$next_version" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag ${{ env.NEXT_VERSION }} -m "Tag for release ${{ env.NEXT_VERSION }}"
          git push origin ${{ env.NEXT_VERSION }}

      - name: Update latest tag
        run: |
          if git rev-parse latest >/dev/null 2>&1; then
              git tag -d latest
              git push origin :refs/tags/latest
          fi
          git tag latest -m "Update latest tag to ${{ env.NEXT_VERSION }}"
          git push origin latest

      - name: Create new tag and release using gh
        run: |
          echo "Waiting for 10 seconds before creating the release..."
          sleep 10
          gh release create ${{ env.NEXT_VERSION }} --notes "Release ${{ env.NEXT_VERSION }}"
